src/components/ModalPayment/ModalPayment.tsx, src/components/ModalPayment/SquareModal.tsx, src/components/ModalPayment/styles.module.scss, src/components/OwnerPanel/OwnerPanel.tsx, src/components/OwnerPanel/styles.module.scss, src/components/SellerPage/SellerPage.tsx, src/components/StoreInfo/StoreInfo.tsx
extra info section hides null. Also picked up the t&c hitbox minor fix, hovering underlines the text and you can click anywhere in the container. open to suggestions on anything better!
=> extrainfo fix, t&c hit box is bigger

src/components/ModalPayment/SquareModal.tsx, src/components/ModalPayment/SubmissionButton.tsx
Demo: https://drive.google.com/open?id=1m51ZlR56oLG4DVIsVw8YMa9r6LXxVKrJ
Disables the button right after hitting submit. The button can be re-enabled by clicking on any input field.
=> Disable button to prevent duplicate donations/purchages

src/utilities/api/interactionManager.ts
Pass idempotency_key to the server so it can be used to dedup charges
Testing plan:
Verified  `idempotency_key` is set in the HTTP params
```
request: {http_method: "POST", query_url: "https://connect.squareupsandbox.com/v2/payments",…}
headers: {accept: "application/json", content-type: "application/json; charset=utf-8",…}
http_method: "POST"
parameters: "{"source_id":"cnon:CBASEBoAZRQl0jCLqDiBEDLaDQ0","idempotency_key":"49621545-c41f-4770-98c6-c12d4c21c4f7","amount_money":{"amount":1000,"currency":"USD"},"buyer_email_address":"danthaman44@gmail.com","note":"Thank you for supporting Shunfa Bakery.","location_id":"E4R1NCMHG7B2Y"}"
query_url: "https://connect.squareupsandbox.com/v2/payments"
```
Verified  `idempotency_key` is received by the Rails ChargesController
```
Started POST …
```
=> Pass idempotency_key in charges POST request

src/index.scss
Talked to Nanxi offline, the red is only supposed to be a hover state for the buttons. 
Reverted the base color to black/white and implemented the hover state.
=> Updated seller modal hover states

src/components/OwnerPanel/styles.module.scss, src/components/ProgressBar/ProgressBar.tsx, src/components/ProgressBar/styles.module.scss
Left a table style in the wrong .scss file, tooltip is misaligned in merchants directory page
=> Quickfix for numsupporters tooltip on merchants page

src/components/ModalAmount/ModalAmount.tsx
Line 99 Blocks users from entering ' .+-e ' into the number input field for donations. 
Users are still able to copy paste invalid input to the input box but the regex check will disable the next button on a non-numeric input.
=> Block non-numeric values to donation/voucher amount field

src/components/ModalAmount/ModalAmount.tsx, src/components/OwnerPanel/OwnerPanel.tsx, src/utilities/hooks/ModalPaymentContext/reducers.ts, src/utilities/hooks/ModalPaymentContext/types.ts
$5 is our second most common donation amount. Since we don't have a menu option for $5, lets prefill it into the input form to reduce friction for people who want to make small donations
=> Prefill  donation amt to reduce friction

package-lock.json, package.json, src/components/App/App.tsx, src/components/MerchantsPage/DonationPool.tsx, src/components/MerchantsPage/MerchantsPage.tsx, src/components/Modal/Modal.tsx, src/components/ModalAmount/ModalAmount.tsx, src/components/ModalBuyMeal/ModalBuyMeal.tsx, src/components/ModalPayment/SubmissionButton.tsx, src/components/OwnerPanel/OwnerPanel.tsx, src/components/SellerPage/SellerPage.tsx
Test plan:
-Verified tracking events are being sent via FB Pixel Helper Chrome extension
-Verified tracking events show up in Ads Manager
=> Added Facebook tracking for user interactions

.env.production
Adding FB pixel ID to env.production to enable pixel tracking for ads. We will need to remove env.development from github after this since this ID is private.
=> Adding FB pixel id

src/components/OwnerPanel/styles.module.scss
Adds ellipsis to overflowing button text on small screen sizes
iPhone SE:
Bigger mobile sizes like iPhone 8:
=> Fixes owner panel button overflow on really small screens

src/locales/cn/translation.json
[Trello card](https://trello.com/c/TsaP1d6C/485-there-are-some-mistakes-on-our-merchants-page-the-following-sentences-should-be-%E5%A6%82%E6%9E%9C%E4%BD%A0%E4%B8%8D%E5%A4%AA%E7%A1%AE%E5%AE%9A%E6%8D%90%E6%AC%BE%E7%BB%99%E5%93%AA%E4%B8%AA%E5%95%86%E5%AE%B6%EF%BC%9F)
=> Fixing a tiny typo in the Chinese text for donation pool

src/components/App/App.tsx, src/components/Loader/Loader.tsx, src/components/MerchantsPage/ContributionBar.tsx, src/components/MerchantsPage/MerchantNavBar.tsx, src/components/OwnerPanel/OwnerPanel.tsx, src/pages/VoucherRedemption/Amount.tsx, src/pages/VoucherRedemption/Complete.tsx, src/pages/VoucherRedemption/Confirm.tsx, src/pages/VoucherRedemption/Landing.tsx, src/pages/VoucherRedemption/MoreInfo.tsx, src/pages/VoucherRedemption/VoucherRedemption.tsx, src/pages/VoucherRedemption/styles.ts, src/utilities/api/interactionManager.ts, src/utilities/hooks/VoucherContext/types.ts
New:
- Added checks for single_use variable and modifying the pages and flow when this is true
- Various text changes when in the single_use flow
Changes to both flows:
- Improved error handling on the amount input box
- Accepts inputs between 5¢ and the full amount
- Error state now disables and greys out the "Next" Button
- Error state changes the border to red
- Added floating $ sign to input box
- Fixed logic on when to invert the colors for the More Info tool tip (code is intentionally verbose to be more readable)
- Flexbox changes to allow spacing to be added more naturally on different size devices
- Changed the back / cancel buttons to more closely match the Figma design
- Removed the z-index the More Info div which was blocking the input box when not popped out
General code …
=> Single Use Voucher Redemptions and Overall Redemption Flow Tweaks

src/pages/VoucherRedemption/Confirm.tsx, src/pages/VoucherRedemption/Landing.tsx, src/pages/VoucherRedemption/VoucherRedemption.tsx, src/utilities/hooks/VoucherContext/types.ts, src/utilities/hooks/helpers.ts
-This fixes a bug which causes the redemption flow to break because it can't render the location from the backend correctly.
-Also fixes a minor bug where the `color` prop in the `Button` component wasn't being set properly due to a missing semicolon
Before:
After:
=> Fixed critical bug with location rendering in the redemption flow

src/pages/VoucherRedemption/Landing.tsx, src/pages/VoucherRedemption/MoreInfo.tsx
Talked to @nanxiy , we want to make the entire voucher card tappable in the redemption flow instead of just the "click to begin redeeming your voucher" text. The info icon and tooltip still handle tap separately.
Test plan:
=> Make entire card tappable in redemption flow

src/pages/VoucherRedemption/Amount.tsx
Fixes two bugs:
1. Resets the state amount to 0 if the user `Cancels` out of the redemption flow
2. Prefills the amount input with the existing state amount if the user hits `Back` from the confirmation screen
Test plan:
=> Fixed back/cancel state bugs in redemption flow

src/components/ModalPayment/SquareModal.tsx, src/index.scss
This PR fixes https://github.com/sendchinatownlove/sendchinatownlove.github.io/issues/175
- Disabled submit button after payment submission, Square will also block duplicate payment on their side though, thus this issue should not be a priority.
- Changed the disabled button cursor style to default.
Before (I'm keeping clicking the submit button, and you could see the request do have been sent multiple times):
After:
=> Disable payment confirm button after form submission

src/pages/VoucherRedemption/Amount.tsx, src/pages/VoucherRedemption/Complete.tsx, src/pages/VoucherRedemption/Confirm.tsx, src/pages/VoucherRedemption/MoreInfo.tsx, src/pages/VoucherRedemption/StoreBanner.tsx, src/pages/VoucherRedemption/VoucherRedemption.tsx, src/utilities/hooks/VoucherContext/types.ts
Fixed bug where the owner name and image was showing up instead of the store name and image
Test plan:
=> Fixed owner name bug in redemption flow

src/components/ModalBuyMeal/ModalBuyMeal.tsx
Previously in the modal flow we set amount default to 5--and were pulling that for the GAM initial state. Setting to 1 now instead.
=> Setting GAM initial meal amounts always to 1

src/components/MerchantsPage/gam/CampaignListItem.tsx, src/components/MerchantsPage/gam/CampaignProgressBar.tsx, src/components/MerchantsPage/gam/GiftAMealPage.tsx, src/components/MerchantsPage/gam/styles.module.scss
-Render Seller logo_image_url instead of placeholder melonpanna logo in the Campaign list item
-Remove GAM button for inactive campaigns
-Added description text to video
-Updated with @nanxiy 's latest changes to the progress bar to reduce text overflow
Test plan
=> UI polish for GAM page

src/components/ProgressBar/ProgressBar.tsx
**Changes made**:
1.	Vouchers/Donations hover when cursor is on progress bar (instead of the supporters text)
2.	Formatted the voucher and donations dollar amount to be consistent with amount raised and target amount below it (before: $2960, after: $2,960) . 
**Before**: 
**After**:
Suggestions:
1.	Do we also want to round the amounts in the box (e.g. $916.75 to $916)?
2.	The tooltip placement covers the merchant description (on all merchants page) and the merchant name (on individual merchant page). Do want to change this to bottom or leave as it is? 
**Current (top placement)**:
**Bottom placement**:
=> Hover on merchant progress bar/format dollar amounts

src/components/App/App.tsx, src/components/Navbar/NavBar.tsx
I noticed the bottom border under Donate in the nav bar is not showing when it's the active page. I could have changed  '/merchants' to  '/all'' in `isMerchantsPathActive` but I did some refactoring (heh). Let me know if you want me to revert to what we had. I also added some styling to make it closer to the Weebly underline.
**Currently:**
https://merchant.sendchinatownlove.com/all
**Now:**
**Compared to Weebly's underline**
=> FIX: Donate nav link

src/components/MerchantsPage/gam/CampaignListItem.tsx
https://merchant.sendchinatownlove.com/gift-a-meal-home is currently messed up because the images are too large. Adding image size limits 
Test plan:
-Seeded DB with large merchant logo images, verified they render correctly
=> Enforce image size limits for Campaign List Item

src/components/MerchantsPage/gam/CampaignListItem.tsx
The `desktopScreens` media query was failing to shrink large images properly, so removing it.
Desktop
Mobile
=> Fixed Campaign image sizing issue

src/components/MerchantsPage/gam/GiftAMealPage.tsx, src/components/MerchantsPage/gam/styles.module.scss
- Updated to use public video
- Added top and bottom margin to the Video per @nanxiy 's feedback
- Added key to Campaign list items to suppress React warning https://reactjs.org/docs/lists-and-keys.html#keys
Desktop:
Mobile:
=> Updated GAM page video component

src/components/MerchantsPage/gam/CampaignListItem.tsx
Need to divide price_per_meal by 100 to show the price in dollars
Before:
After
=> Fixed monetary conversation in Campaign GAM modal

src/components/OwnerPanel/OwnerPanel.tsx
The initial implementation was making two HTTP requests, one of which had a null `seller_id`, and fails. This removes the duplicate request
Before:
After:
=> Fixed bug when calling seller's campaign endpoint

src/components/MerchantsPage/gam/CampaignListItem.tsx
Saves vertical space so we can include longer descriptions
Test plan
=> Make distributor link in-line with description to save space

src/pages/PassportRedemption/Faq.tsx
I'm not sure how it looks on dev but ultimately we want it to look like this which was from my old branch/static page - alice/passportfaq (the screenie below). I just copy and pasted the markup for the FAQ and made no styling changes to dev.
=> Fill actual passport FAQ content

src/pages/PassportRedemption/TrackScreen.tsx
The IG tooltip was hiding after 1.5 seconds, which is too little time to read.
Before:
After:
=> Fixed bug where tooltip hides too early

src/pages/PassportRedemption/RedemptionSelectScreen.tsx
-Increased SingleRewardContainer height to fit location
-Added bottom padding to RewardsContainer so haze doesn't obscure bottom most reward
-Disable click interaction on the reward container if there are no rewards
Before:
After:
=> Fixed bugs in rewards redemption screen

src/pages/PassportRedemption/RedemptionClaimScreen.tsx
Addresses were being displayed incorrectly since the getLocationById was using the sponsor_id instead of the sponsor's location_id. 
I wasn't able to test this locally since I was running into an error while adding a ticket, but I think this should be the fix?
=> Fix passport redemption location using sponsor_id instead of location_id

src/pages/PassportRedemption/RedemptionSelectScreen.tsx
The buffer element wasn't showing up under the reward cards so the last cards were partially hidden by fade again. I changed grid properties to fix this.
=> fixed grid properties to show buffer again

index.html, src/pages/PassportRedemption/TrackScreen.tsx
**To prevent auto zoom:** 
"The browser will zoom if the font-size is less than 16px and the default font-size for form elements is 11px (at least in Chrome and Safari." 
https://stackoverflow.com/questions/2989263/disable-auto-zoom-in-input-text-tag-safari-on-iphone
=> change font size to 16px in text field

src/components/ModalBuyMealNew/styles.module.scss
- reduced line height for header text to save vertical space
- make GAM instructions display in a single column if screen size is smaller than 400px
Before:
After:
=> Updated spacing and alignment in GAM modal

src/components/MerchantsPage/gam/CampaignListItem.tsx
Spillage between 900px - to desktop size (e.g. split screen). It is more obvious if campaign description is long. Quick fix - I changed max-height to 800px. Should give ok leeway for long descriptions. Alternative is to increase tablet screen threshold...
**Before:**
**After:**
(956 x 850 below)
=> GAM Campaign List: increase max-height to 800px for desktop

src/pages/PassportRedemption/Passport.tsx
Otherwise the modals will stack on top of eachother
=> Disable the email modal if the Lyft reward modal is showing

src/pages/PassportRedemption/LyftPromo.tsx
Remove duplicate css that is based on the base-button from index.scss as well as same css in the lyft buttons
Min-width - comes from the index.scss which is why the buttons are long
Take it or leave these changes
=> Refactor Lyft css

package.json, src/components/StoreInfo/StoreInfoContainer.tsx, src/components/StoreStory/StoreStory.tsx, src/components/StoreStory/styles.module.scss, yarn.lock
Background
- [react-markdown](https://github.com/rexxars/react-markdown) seems to be the cleanest, easiest way to achieve this
- It also escapes HTML and keeps us safe from XSS attacks
- It seems a little rusty in terms of maintenance, but I still think it's worth adopting
- All of our text is backwards-compatible, so nothing should break
Work completed
- Used `react-markdown` to render the story and summary sections of the merchant page
- Added some standard brand styling for links, everything else is standard
- Shared styling as best as we could
Next steps
- Update the stories in our database with markdown
Screenshots:
=> Using react-markdown to render the merchant summaries and stories

src/components/Footer/Footer.tsx, src/components/MerchantsPage/gam/CampaignListItem.tsx
- Give more context to the GAM partner link (and open in new tab) after the campaign description.
- Remove z-index on footer icon since Dan fixed merchant banner overlap some time ago
=> Small GAM clean up

src/pages/PassportRedemption/TicketRow.tsx
When a person had stamps that were
eligible to be redeemed and they did
not redeem the reward, the passport
stamps are covered by the Send to Email
button.
This created a poor UX, so I moved the
button to the bottom and changed the
text to be "Redeem"
=> Show all passport stamps

package.json
Upgrading the react-router-dom typing from 5.1.3 -> 5.1.5 fixed some errors I was getting locally w/ the history typing:
```
Overload 1 of 2, '(props: Readonly<RouterProps>): Router', gave the following error.
Type 'History<unknown>' is not assignable to type 'History<PoorMansUnknown>'.
The types of 'location.state' are incompatible between these types.
Type 'unknown' is not assignable to type 'PoorMansUnknown'.
Type 'unknown' is not assignable to type '{}'.
Overload 2 of 2, '(props: RouterProps, context?: any): Router', gave the following error.
Type 'History<unknown>' is not assignable to type 'History<PoorMansUnknown>'.  TS2769
93 | 
94 |   return (
> 95 |     <Router history={history}>
|             ^
96 |       <Suspense fallback={<Loader isPage={true} />}>
97 |         <Switch>
98 | …
```
=> Upgrade @types/react-router-dom to 5.1.5

src/components/Footer/Footer.tsx
Fix the console error (screenshot below) by adding a key to the `LinkItem` in `FooterComponent`
=> Fix console error - add key to social media `LinkItems` in `FooterComponent`

src/components/App/App.tsx, src/components/Navbar/NavBar.tsx, src/consts.ts
Create Page enum for pages (all, seller, etc.) rather than using strings ('all', 'seller', etc.) for the pages. Also did a bit of alphabetizing and rearranging imports on the files I touched.
=> Create Page enum for pages (all, seller, merchant, etc.)

src/components/MerchantsPage/ContributionBar.tsx, src/components/MerchantsPage/MerchantsPage.tsx, src/locales/cn/translation.json, src/locales/en/translation.json, src/utilities/api/types.ts, src/utilities/hooks/ModalPaymentContext/types.ts
Add GAM to total contributions bar on all merchants page. Also did a couple refactors in the files I touched / added some more typings. See screenshots below for the contributions bar UI w/ various donation / GAM / gift card amounts.
Depends on: https://github.com/sendchinatownlove/ruby/pull/261
Trello ticket: https://trello.com/c/2Ncvuvix/609-add-gam-in-total-raised-contribution-bar-on-merchants-page
=> Add GAM to total contributions bar on all merchants page

src/components/MerchantsPage/ContributionBar.tsx
- Correctly display $ amounts (round to nearest dollar)
- Adjust left/right style for gift a meal text
=> Small changes to contributions bar

src/pages/MerchantVoucherDashboardV2/VoucherTable.tsx, src/pages/MerchantVoucherDashboardV2/styles.module.scss
Merchant dashboard v2 - hacky fix for print bug. Before, only the first page would render in the print view, so if there were hundreds of gift cards, only the first 20 would be printable. This was basically due to the fact that the react-filterable-table component doesn't rerender when the pageSize prop changes. I created this hacky fix by looking into the internals of the table. We're going to manually call the method that triggers the page size to change in the react-filterable-table.
=> Merchant dashboard v2 - hacky fix for print bug

src/components/MerchantsPage/styles.module.scss
Quick CSS fix to center the highlight and merchant containers on iPad (see below; tested with Chrome's developer tools).
I didn't change the sizes of any of the containers so the left and right margins are not the same size, but it should be centered at least. Happy to talk to design about this if its a priority.
**Before** ![image](https://user-images.githubusercontent.com/20375084/97791154-9b0ff480-1ba5-11eb-8ae3-3582b69c2dd3.png)
**After**
=> centered merchant and highlight containers on ipad

src/components/MerchantsPage/gam/GiftAMealPage.tsx
API endpoint returns campaigns ordered by least recent end date first. We want the past campaigns to show the most recent end date first. So if we `reverse()` on the frontend then it will accomplish this.
We could do `sort(
(a, b) => a.end_date < b.end_date ? 1 : (a.end_date > b.end_date ? -1 : 0)
);` if we really wanted to but `reverse()` is good for now.
=> Sort past campaigns by recent end date

src/components/LightUpChinatown/LightUpChinatownPage.tsx
The LightUpPage won't load on staging/local if there is no backend project. This adds a safety check to make sure it loads
=> Add null safety check to Projects fetch in LUC progress bar

src/components/MerchantsPage/gam/CampaignListItem.tsx
front end is broken and isn't showing the seller x distributor title and the learn more about part
we should probably eventually remove distributor_id in campaigns
=> Use seller_distributor_pairs for gam 

src/components/LightUpChinatown/LightUpChinatownPage.tsx, src/components/ModalPayment/ModalConfirmation/ModalConfirmation.tsx, src/index.scss
List of Changes
- Modify LUC content max width and add padding to match the mockup 
- Fix Finish button on the payment complete modal not spanning the entire screen on mobile devices
- *HOTFIX* LUC modal not closing on pressing the Finish button when a transaction is completed. This should be replaced with a more robust solution that can differentiate between an actual seller_id and a project_id/ something that resembles a project_id
=> Some Light Up Chinatown Page fixes

src/components/MerchantsPage/gam/CampaignListItem.tsx, src/components/MerchantsPage/gam/FiscalSponsor.tsx, src/components/MerchantsPage/gam/MegaGamListItem/MegaGamListItem.tsx, src/utilities/api/interactionManager.ts, src/utilities/api/types.ts
Add fiscal sponsor to mega gam campaign. Created a shared FiscalSponsor component to be used by regular and mega gam campaigns
Desktop:
Mobile:
=> Add fiscal sponsor to mega gam campaign

src/components/MerchantsPage/gam/CampaignListItem.tsx, src/components/MerchantsPage/gam/CampaignProgressBar.tsx, src/components/MerchantsPage/gam/MegaGamListItem/MegaGamListItem.tsx
Fixing a lot of css for regular/mega gam campaigns. There's lots of subtle differences in margin, font size, layout, etc. between active/mobile campaigns that make this code pretty sloppy
=> Fixing a lot of css for regular/mega gam campaigns

src/components/ModalPayment/ModalAmount/ModalAmount.tsx, src/index.scss
Added margin to fix:
Reverted to original button styling as the confirm button looks like this on mobile:
We can make the modal button width back to 100% when we decide to move the back button to the top of the modal
=> Payment modal quick fix

src/components/MerchantsPage/gam/CampaignListItem.tsx
=> Fix margin on campaign list item image

src/components/ModalPayment/ModalCardDetails/ModalCardDetails.tsx
Bug:
Fixed bug and removed sellerName since Donation Pool disclaimer doesn't take a sellerName
=> Seller name in disclaimer

src/components/MerchantsPage/gam/MegaGamListItem/MegaGamListItem.tsx
- We have used React-Markdown before https://github.com/sendchinatownlove/sendchinatownlove.github.io/pull/328/files 
- To link Apex for Youth, the description needs to be updated to: 
`That’s why we’re teaming up with [Apex for Youth](https://www.apexforyouth.org/)`
=> Mega-GAM: Use React-Markdown for description render

src/pages/PassportRedemption/SignIn/uploadScreen.tsx
removed onblur. issue is onblur gets called before onclick, which is why the search bar wasn't populating after selecting a merchant
=> remove onblur

src/components/ModalPayment/ModalAmount/ModalAmount.tsx, src/locales/cn/translation.json, src/locales/en/translation.json
Trello Card: https://trello.com/c/9kWVBoet/780-update-no-active-gam-campaigns-button-modal-text
I can't figure out why the `<p>` footer text won't take up the entire width in chrome, unfortunately, but I figure it's a minor piece.
Just to clarify the word done:
- Header and body changes to Gift-a-Meal Donation for when there isn't a campaign
- Footer with the disclaimer always shows for all scenarios
It's not great that I have that if statement there, but the work to change the structure, I think, may be a bit more than expected. Do we want to eventually remove business logic from the `Modal` component so the callers just pass in what it wants to render?
=> Update no active GAM campaigns button modal text and set modal footer text

src/components/LightUpChinatown/LightUpChinatownPage.tsx
We're seeing a bunch of errors on the back-end as the query for all the amount raised for LUC is huge now! (Kudos to us!). Let's save our backend some stress and hard-code this number as the campaign's closed anyway.
Screenshot of all recent timeout failures on this endpoint:
(It's also not the most optimal query, but we can fix that separately)
=> Hard-coding LUC amount raised

src/components/StoreInfo/StoreGalleryTab.tsx, src/components/StoreInfo/StoreInfoContainer.tsx
[Ticket](https://trello.com/c/gdtAR4zu/498-add-arrow-buttons-for-the-gallery-images-so-you-can-click-through-them-in-modal-view)
Description:
Adds bumper buttons for a store's gallery modal so the user 
can scroll through the images without having to exit the Modal.
=> Add arrow buttons for Store Gallery Tab Images Modal

src/components/ModalPayment/ModalConfirmation/ModalConfirmation.tsx, src/locales/cn/translation.json, src/locales/en/translation.json
Outdated confirmation text, currently looks like this:
Moved things into the translation files instead of hardcoding. 
The original trello card https://trello.com/c/EgneaM8N/750-voucher-check-out-page-and-receipt-needs-to-be-updated?menu=filter&filter=alice,label:Engineering
=> Update checkout confirmation text

src/components/Navbar/NavBar.tsx
Changing the NavBar to be sticky during mobile viewport sizes.
Two things to note:
- It looks like for whatever reason styled-components isn't updating based on prop changes here - https://github.com/sendchinatownlove/sendchinatownlove.github.io/blob/5217c9e7c7ab5079d21d2656ee5086c0bb277419/src/components/Footer/Footer.tsx#L50 As a result, I opted for a fairly janky solution of changing the `NavLink` margins to padding instead and hiding the footer behind a white background. Not perfect, but I couldn't figure out why the the footer display refused to change to None on props change
- Added a classname specifically for the Logo to target it for CSS purposes
=> Sticky navbar

src/components/Navbar/NavBar.tsx, src/components/Navbar/styles.module.scss
- conditionally applying sticky logic only when the menu is closed
- tested on an iPhone SE v1 on iOS 14.3
- I think all our conditionality in the inline `styled` CSS is working... we should look into it and fix sometime
=> fix: navbar open menu no longer broken for some iPhone users

src/components/Navbar/NavBar.tsx, src/components/Navbar/styles.module.scss
https://trello.com/c/pt5EGq1I/838-bugfix-for-sticky-navbar-on-ios
Implementing previous fix using a conditional to apply `position: sticky` - this time with media query so this only occurs on small screens.
=> Sticky Navbar fix with media query
