sendchinatownlove/sendchinatownlove.github.io

- src/components/Home/styles.module.scss
Looks a lil better than before
> Fix home line heights for mobile

- src/components/ModalAmount/ModalAmount.tsx
The check should be for strictly less than 5, not less than or equal
> Fixed minimum amount verfication in donation flow

- src/components/ModalAmount/ModalAmount.tsx
- src/components/ModalPayment/SquareModal.tsx
- src/consts.ts
- src/utilities/api/interactionManager.ts
Linting/formatting latest changes
> no message

- src/components/Footer/Footer.tsx
> Link logo to home

- src/components/ModalPayment/SquareModal.tsx
- src/utilities/api/interactionManager.ts
- src/utilities/api/types.ts
> Move seller_id for square_payment to charges body

- .github/workflows/deploy.yaml
- package.json
allows deploy from merge to dev to master
> updating publish branch

- .github/workflows/deploy.yaml
- package.json
Reverts sendchinatownlove/sendchinatownlove.github.io#75
> Revert "updating publish branch"

- src/components/OwnerPanel/OwnerPanel.tsx
- src/index.scss
Design: https://www.figma.com/file/I0XPeX6re8t14J4nZOvVNp/Send-Chinatown-Love?node-id=1517%3A588
Desktop:
Mobile:
> Updated Owner panel to latest designs

- src/components/ModalAmount/ModalAmount.tsx
- src/components/ModalConfirmation/ModalConfirmation.tsx
- src/components/ModalPayment/ModalPayment.tsx
- src/components/ModalPayment/SquareModal.tsx
- src/consts.ts
> Updated copy from gift card to voucher

- src/components/App/App.tsx
- src/components/MerchantsPage/styles.module.scss
fixed mobile view so there is no spilling & updated url to /merchants
> changed to merchants url and fixed mobile view

- src/components/OwnerPanel/styles.module.scss
- src/index.scss
Updated fonts and colors to match design spec https://www.figma.com/file/I0XPeX6re8t14J4nZOvVNp/Send-Chinatown-Love?node-id=1517%3A588
> Fixed up owner panel hover states

- package-lock.json
- package.json
- public/index.html
- src/components/MerchantsPage/styles.module.scss
- src/components/OwnerPanel/OwnerPanel.tsx
- src/components/OwnerPanel/styles.module.scss
- src/index.scss
- tsconfig.json
- yarn.lock
Social icons implemented via https://github.com/nygardk/react-share
> Added social share icons to seller page

- package.json
- src/index.tsx
- yarn.lock
Reverts sendchinatownlove/sendchinatownlove.github.io#105
> Revert "update og tag snapshotting for react rendering"

- src/components/ModalPayment/SquareModal.tsx
- src/utilities/api/interactionManager.ts
- src/utilities/api/types.ts
> Added email subscription checkbox

- src/components/ModalBuyMeal/ModalBuyMeal.tsx
- src/components/ModalConfirmation/ModalConfirmation.tsx
- src/components/ModalPayment/SquareModal.tsx
- src/components/ModalPayment/styles.module.scss
- src/utilities/api/interactionManager.ts
> Added second half of Buy A Meal flow

- src/components/ModalAmount/ModalAmount.tsx
- src/components/ModalAmount/styles.module.scss
- src/components/ModalBuyMeal/ModalBuyMeal.tsx
- src/components/ModalPayment/SquareModal.tsx
- src/index.scss
- src/locales/en/translation.json
-Updated header font and copy in donation/voucher flow
-updated donation amount input box
-Fixed bug where "X" icon was not showing in Buy A Meal flow
> Polished up UI in purchase flow

- src/components/Navbar/NavBar.tsx
> Added underline to Merchant navlink to mimic Weebly

- package-lock.json
- package.json
- src/components/OwnerPanel/OwnerPanel.tsx
> Added copy to clipboard button

- src/components/ModalAmount/ModalAmount.tsx
- src/components/ModalPayment/SquareModal.tsx
-Updated spacing and fonts to more closely match Figma design
-Updated input box border color to match design
-Made '$' in front of custom amount permanent
-Formatted code with yarn
> UI polish for donation/voucher flow

- src/components/OwnerPanel/OwnerPanel.tsx
Test plan:
Verified the UI can process the /seller cost_per_meal value in cents, and posts to /charges with a value in cents
> Process seller cost per meal as cents

- src/components/MerchantsPage/styles.module.scss
- src/components/Modal/Modal.tsx
- src/components/ModalAmount/ModalAmount.tsx
- src/index.scss
Fixes for #140 and #141 
Plus some styling changes to match spec
* transparent background on inactive filter buttons on merchants page
* flyer message left aligned
Before:
After:
> fix for #140, #141

- src/components/ModalAmount/ModalAmount.tsx
- src/components/ModalBuyMeal/ModalBuyMeal.tsx
- src/components/ModalBuyMeal/styles.module.scss
- src/components/OwnerPanel/OwnerPanel.tsx
- src/components/OwnerPanel/styles.module.scss
- src/locales/en/translation.json
* Gift meal button spans panel width
DesktoP:
Mobile:
* Gift meal amount selection view:
Desktop:
Mobile:
> Fixes for few gift a meal issues

- src/components/OwnerPanel/OwnerPanel.tsx
- src/components/OwnerPanel/styles.module.scss
> Fix #162 to match figma

- src/components/ModalBuyMeal/styles.module.scss
> Made Gift Meal images responsive

- src/components/ModalBuyMeal/ModalBuyMeal.tsx
prevent the user from donating more than 10000 dollars worth of meals. This is to be consistent with our donation upper bound.
> Upper bound on meals

- src/pages/VoucherRedemption/Amount.tsx
- src/pages/VoucherRedemption/Complete.tsx
- src/pages/VoucherRedemption/Confirm.tsx
- src/pages/VoucherRedemption/Landing.tsx
- src/pages/VoucherRedemption/StoreBanner.tsx
- src/pages/VoucherRedemption/styles.ts
- temp fix to have components stacked on top of each other instead of overlapping
> quick fix to voucher page

- src/components/OwnerPanel/OwnerPanel.tsx
The api already returns https:// which was the problem and was appending
unnecessary protocol
> fix menu url on merchants page

- src/components/Navbar/NavBar.tsx
Noticed that our website has two different components for responsive and
non-responsive parts
> Add nbsp for full size website

- src/components/MerchantsPage/MerchantsPage.tsx
- Forgot that we had a SCL donation pool merchant card. Needed to add this line since that card doesn't include any locations and was throwing errors
> added condition for empty locations

- src/components/MerchantsPage/gam/CampaignListItem.tsx
- src/components/MerchantsPage/gam/CampaignProgressBar.tsx
- src/index.scss
- src/locales/cn/translation.json
- src/locales/en/translation.json
> Created progress bar component for campaigns

- src/components/MerchantsPage/DonationHighlightBox.tsx
- src/locales/cn/translation.json
- src/locales/en/translation.json
- Will use this as the template for the new GAM entry point box as well
- Not adding this to the Merchant page until the new GAM experience is ready
Desktop:
Mobile
> Created updated entry point component for pool donations

- src/components/MerchantsPage/GiftMealHighlightBox.tsx
- src/locales/cn/translation.json
- src/locales/en/translation.json
- src/utilities/general/StoreImages.tsx
> Created GAM entry point component

- src/components/MerchantsPage/gam/CampaignListItem.tsx
- src/components/MerchantsPage/gam/GiftAMealPage.tsx
- src/utilities/api/endpoints.ts
- src/utilities/api/interactionManager.ts
1. Added support for calling /campaigns endpoint to interactions manager
2. Added logic to fetch and render campaigns to GiftAMealPage
3. Fixed up some CSS responsiveness issues in CampaignListItem
Test plan
> Wired GAM page to campaigns endpoint

- src/components/MerchantsPage/gam/CampaignListItem.tsx
- src/components/MerchantsPage/gam/GiftAMealPage.tsx
- src/utilities/api/endpoints.ts
- src/utilities/api/interactionManager.ts
- src/utilities/api/types.ts
> Wired up GAM page with Campaign and Seller information

- src/components/Logos/Logos.tsx
- src/components/Navbar/NavBar.tsx
**Changes**
* Aligned hamburger menu icon
* Changed size and alignment of SCL icon in compact menu to be consistent with Weebly's compact menu
* Added styling to nav bar to be consistent with the other pages
**Before**:
https://trello-attachments.s3.amazonaws.com/5e777be61d2e4a20cf1ab0ff/5f1734ded4528611dfff357f/9157a6afe096b55f8c0d6095766e9b1d/movie.mp4
**After:**
**Before**
**After**
> Fix hamburger menu and nav bar styling

- src/components/MerchantsPage/gam/CampaignListItem.tsx
- src/components/OwnerPanel/OwnerPanel.tsx
Merchant sells vouchers:
Merchant doesn't sell vouchers:
> Make GAM button full width if the merchant doesnt sell vouchers

- src/components/OwnerPanel/OwnerPanel.tsx
- src/utilities/api/interactionManager.ts
Migrate the owner panel from using Seller model data to Campaign model data for GAM
Test plan:
Verified GAM flow works from Owner Panel
Verified charge request is send to backend with correct campaign_id
> Update Owner panel to use Campaigns API

- src/components/OwnerPanel/OwnerPanel.tsx
Fixing a bug where the checkout flow modal was only being added to the DOM if there was an active campaign:
Test plan:
Tested both GAM and non-GAM merchants to verify that the checkout flow works now.
> Fixed bug with checkout flow not opening on non-GAM merchants

- src/components/Navbar/NavBar.tsx
- Also adjusting width of the nav bar so it's not so crowded
- Looks good on all widths
> Adding SCL Food Crawl link to nav bar and adjusting width

- src/pages/PassportRedemption/Passport.tsx
Made sorting algo to be more stable and concise
Fixed year/date in passport
> Sorting algo/fix passport year

- src/pages/PassportRedemption/TrackScreen.tsx
- src/pages/PassportRedemption/style.tsx
**note: i started this pr yesterday, so there are a couple changes in here. going forward i can make one change per commit 
changes in this pr:
1. all ticket codes will be sent to the backend as capitalized values 
2. bolded "for digital giveaway"
3. added "optional" under insta handle text field
4. will only be able to see the button "View My Tickets" when an email is entered 
5. updated tooltip to disappear after 30 seconds (since last touch) from 1.5 seconds lol <-- lmk if we want to make this even longer
6. changed e.key to e.keyCode !== 8; apparently androids read keyCode & not key? Not sure, need to merge and test on an android phone. but this change works on chrome so far
> styling updates to trackScreen

- src/pages/PassportRedemption/TrackScreen.tsx
Changing input type from "text" to "tel" to see if that works for android browsers, currently works on browser
based off comments from: 
https://github.com/substance/substance/issues/982
> updating input to tel to test on android browsers

- src/pages/PassportRedemption/TrackScreen.tsx
- taking out hyphen auto population until i figure out how to make it work on androids :(
> removing autopopulated hyphen from ticket field

- src/pages/PassportRedemption/Passport.tsx
> Fixed floating button covering bottom row of stamps

- src/pages/PassportRedemption/Faq.tsx
Overall:
- Removed indented/sub-bullet points and used normal bullet points
- Font size change for content and view rewards title to 12px and padding per Figma design
- Removed underline for Month of Sept
- Fix SCL FoodCrawl links
> Fix actual FAQ Content 

- src/pages/PassportRedemption/Faq.tsx
> Redirect view active rewards to food crawl info page

- src/pages/PassportRedemption/Faq.tsx
- src/pages/PassportRedemption/Passport.tsx
Lmk if you find a better way
Iphone SE and some of the smaller phones could be improved but I think it might be tiling issue with how certain phones handle it...
> Make FAQ and Passport Table scrollable/Fix

- src/pages/PassportRedemption/Passport.tsx
- src/pages/PassportRedemption/TicketRow.tsx
This and I made Learn More open in a new window
> Passport table fixes - learn more link and table border

- src/pages/PassportRedemption/TicketRow.tsx
- src/utilities/general/textFormatter.ts
- fixed redeemed at date
- added makePlural function that adds s
> added more strict checks for redeeming tickets/redeemed tickets row.

- src/components/MerchantsPage/gam/CampaignListItem.tsx
Fixes problems like this and makes each campaign card consistent
- ![image](https://user-images.githubusercontent.com/37196330/91876788-bcef0880-ec42-11ea-9b45-b84750f6c5b3.png)
- ![image](https://user-images.githubusercontent.com/37196330/91876924-e9a32000-ec42-11ea-9b67-f63ec4aa472f.png)
> GAM Campaign Item List mobile responsiveness

- src/components/MerchantsPage/DonationHighlightBox.tsx
- src/components/MerchantsPage/MerchantsPage.tsx
- src/components/MerchantsPage/styles.module.scss
- src/components/ModalBuyMealNew/ModalBuyMealPool.tsx
- src/components/ModalBuyMealNew/styles.module.scss
> Expose GAM entry point on Merchants page

- src/components/MerchantsPage/DonationHighlightBox.tsx
> Fix bug in Donation pool highlight button alignment

- src/components/MerchantsPage/gam/CampaignListItem.tsx
- src/locales/en/translation.json
Designs: https://www.figma.com/file/I0XPeX6re8t14J4nZOvVNp/Send-Chinatown-Love?node-id=3727%3A9896
-removed merchant logo image
-fixed image aspect ratios
-updated "View merchant" to "Visit merchant"
-swapped button styles
Desktop:
Mobile:
> Updated GAM page to latest designs

- src/components/Footer/Footer.tsx
Initially I just added wechat but then I saw the new Target Merchants banner blocks the links on desktop so I set the z-index on the links container. 
Additionally:
- Refactored social media links mapping
- Links to be opened in new tab
> Footer - add wechat/fixes

- src/components/MerchantsPage/MerchantDescriptionBanner.tsx
- src/components/MerchantsPage/styles.module.scss
Verified "Download our flyer" link is clickable on desktop and mobile
> Fixed download flyer link being covered by banner

- src/components/MerchantsPage/MerchantsPage.tsx
Nanxi designed/created a weebly page that has the flyers that the user can choose to save:
https://www.sendchinatownlove.com/merchant-flyers.html
lmk what you think of the page
> Replace flyers zip folder with weebly page

- src/locales/cn/translation.json
Removed "and we cover the credit card processing fees."
> Update UX content

- src/pages/PassportRedemption/LyftPromo.tsx
- src/pages/PassportRedemption/Passport.tsx
- src/utilities/api/interactionManager.ts
Success:
Error:
Also ran `yarn format` so there are some unrelated formatting changes
> Wired up Lyft Rewards to API

- src/pages/PassportRedemption/LyftCodeScreen.tsx
- src/pages/PassportRedemption/LyftPromo.tsx
- src/pages/PassportRedemption/PassportDashboard.tsx
- src/utilities/api/endpoints.ts
- src/utilities/api/interactionManager.ts
> Wired up Lyft code to API

- src/pages/PassportRedemption/TrackScreen.tsx
Fix console error by adding a key to the `Icon` component in `Track`
> Fix console error by adding a key to the `Icon` component in `Track`

- src/components/Footer/Footer.tsx
- src/consts.ts
- src/pages/PassportRedemption/TrackScreen.tsx
Share social media link hardcodes across `Footer` and `Track`. I'm new to the codebase and have been taking some time to look through the code. I noticed that we're using the same social media links across the footer and track pages. I figured we could probably reuse some code here
> Share social media link hardcodes across `Footer` and `Track`

- src/components/About/About.tsx
- src/components/Footer/Footer.tsx
- src/consts.ts
- src/pages/PassportRedemption/LyftCodeScreen.tsx
- src/pages/PassportRedemption/Passport.tsx
Create `MAILTO_URL` const and use it across the app. I noticed we were hardcoding the mailto address in the app, so I created a const for it instead and used that in the app.
> Create `MAILTO_URL` const and use it across the app

- src/components/MerchantsPage/gam/GiftAMealPage.tsx
Merge conflicts weren't resolved properly and ended up with duplicate GAM video + caption (Watch how we bring impact to our communties through Gift-a-Meal.)
> GAM video merge fix

- src/components/Navbar/NavBar.tsx
https://merchant.sendchinatownlove.com/all
If you click on Donate or GAM in mobile, it will take you to the right page but the mobile menu is still open and takes up the screen. 
Also smol refactoring
> Close mobile menu when clicked

- src/components/MerchantsPage/gam/CampaignListItem.tsx
- src/locales/cn/translation.json
- src/locales/en/translation.json
- src/utilities/api/endpoints.ts
- src/utilities/api/interactionManager.ts
- src/utilities/api/types.ts
> UI for fiscal sponsor

- package.json
- yarn.lock
Add moment (momentjs.com) to repo for date formatting
> Add moment library to repo

- src/pages/MerchantVoucherDashboardV2/MerchantVoucherDashboardV2.tsx
- src/pages/MerchantVoucherDashboardV2/VoucherDashboard.tsx
- src/pages/MerchantVoucherDashboardV2/styles.module.scss
Refresh button
Full screen:
Smaller screen:
Mobile:
Ticket: https://trello.com/c/sqaKfnSV/605-merchant-dashboard-20
> Merchant dashboard v2 - refresh button

- src/pages/MerchantVoucherDashboardV2/MerchantVoucherDashboardV2.tsx
- src/pages/MerchantVoucherDashboardV2/VoucherDashboard.tsx
- src/pages/MerchantVoucherDashboardV2/styles.module.scss
Custom search bar and hide gam checkbox
Full screen, no filters applied:
Full screen, filters applied:
Smaller screen:
Mobile:
Ticket: https://trello.com/c/sqaKfnSV/605-merchant-dashboard-20
> Merchant dashboard v2 - custom search bar and hide gam checkbox

- src/locales/cn/translation.json
- src/locales/en/translation.json
> Updated GAM second step copy

- src/components/MerchantsPage/ContributionBar.tsx
See https://trello.com/c/FFOmxJlm/666-change-tracker-gam-color-to-hexe49155
> Change contribution bar GAM hex color

- src/components/Navbar/NavBar.tsx
> Fix nav dropdown

- src/components/MerchantsPage/MerchantsPage.tsx
- src/locales/cn/translation.json
- src/locales/en/translation.json
Added the "Our Merchants" title in EN and CN (Nanxi approved translation)
> Added Our Merchants header

- src/components/MerchantsPage/ContributionBar.tsx
- src/components/MerchantsPage/MerchantsPage.tsx
- src/components/MerchantsPage/styles.module.scss
Extended donation bar so that it lines up with the text above on mobile
**Before**
**After**
> Extended width of donation bar for mobile to align with above text

- src/components/LightUpChinatown/LightUpChinatownPage.tsx
- src/components/LightUpChinatown/LightUpFaq.tsx
- src/locales/cn/translation.json
- src/locales/en/translation.json
static faq page for light up chinatown! 
screenshots:
> faq component for light up chinatown

- src/components/LightUpChinatown/DonationDetail.tsx
- src/components/LightUpChinatown/LightUpChinatownPage.tsx
- src/locales/cn/translation.json
- src/locales/en/translation.json
> Added donation detail section

- src/pages/PassportRedemption/PassportVoucher.tsx
Low priority but noticed it when Jacob sent a link over.
> Fix infinite network requests bug in passport printouts

- src/locales/cn/translation.json
- src/locales/en/translation.json
> LUC: Change donation detail

- src/components/ModalPayment/ModalCardDetails/ModalCardDetails.tsx
- src/utilities/api/interactionManager.ts
- Not including a seller ID
- Including the appropriate Project ID
- Including the lucData as metadata (when appropriate)
I know some of this is a little hacky / luc-specific in common code, but I think we have a lot of tech debt in general we'll have to face before our next 'project' :)
Tested with my square dev account -- everything looks good and seems to be working.
> Sending Appropriate info to /charges for LUC

- src/components/LightUpChinatown/LightUpChinatownPage.tsx
-Move it above the FAQ
-Shrink font on mobile
-Add margins
> Make acknowledgements sections more mobile friendly

- src/components/ModalPayment/ModalAmount/LanternForm.tsx
- src/components/ModalPayment/ModalCardDetails/ModalCardDetails.tsx
Full name in shipping address.
> LUC - full name in shipping address in payment

- src/components/Navbar/NavBar.tsx
- src/locales/cn/translation.json
- src/locales/en/translation.json
-  add LUC next to Donate
- remove FOAF from here since they’re no longer donating to us
> LUC in nav bar

- src/components/LightUpChinatown/LightUpChinatownPage.tsx
- src/components/LightUpChinatown/fonts.css
**Added a donation button to the top LUC hero image**.
Please see current vs. my changes below (desktop and mobile included)
**Current**
**Proposed**
> Added LUC donation button on top

- src/components/LightUpChinatown/DonationProgressBar.tsx
The server returns the value in cents
and we assuming it was in dollars
> Fix LUC progress bar

- src/components/Navbar/NavBar.tsx
> Donate drop menu fix

- src/components/LightUpChinatown/DonationProgressBar.tsx
Eg. if percentage raised is 50%
Mobile:
Desktop:
> Donation progress bar fix

- src/components/StoreInfo/StoreLocation.tsx
- src/components/StoreInfo/styles.module.scss
See [Trello Card](https://trello.com/c/eUbW1rrX) for details. Hotfix looks like the attached
> HOTFIX Add margin to locations

- src/components/MerchantsPage/gam/CampaignListItem.tsx
- src/components/MerchantsPage/gam/GiftAMealPage.tsx
- src/components/MerchantsPage/gam/MegaGamListItem.tsx
- src/locales/cn/translation.json
- src/locales/en/translation.json
- src/utilities/api/types.ts
- Correctly sort/order active and inactive GAM campaigns
- Add Mega GAM list item on GAM page
- Type a lot of things
- Little bit of code cleanup
Note that there's a ton of todos still. Will do in followups
Large screen:
Small screen:
Ref https://trello.com/c/tZJj4Wkb/725-megagam-active-mega-gam-campaign-list-item
> Mega GAM partially done, code cleanup

- src/components/MerchantsPage/gam/GiftAMealPage.tsx
- src/components/MerchantsPage/gam/MegaGamListItem/MegaGamListItem.tsx
- src/components/MerchantsPage/gam/MegaGamListItem/SellerDistributorPair.tsx
- src/components/MerchantsPage/gam/MegaGamListItem/index.tsx
- src/locales/cn/translation.json
- src/locales/en/translation.json
- src/utilities/api/types.ts
Seller distributor pairs UI
Depends on https://github.com/sendchinatownlove/sendchinatownlove.github.io/pull/414
> Seller distributor pairs UI

- src/components/MerchantsPage/gam/MegaGamListItem/SellerDistributorPair.tsx
> Fix build - add alt to imgs

- src/components/MerchantsPage/gam/MegaGamListItem.tsx
- src/utilities/api/types.ts
Add campaign display name to mega GAM UI
> Add campaign display name to mega GAM UI

- src/components/ModalPayment/ModalBuyMeal/ModalBuyMealPool.tsx
Added data validation for the max meals amount in GAM checkout, and set the max meals to cost no more than $10K.
**Before** 
**After (using different cost per meals)**
$7
$5
> added max meals to gam checkout

- src/components/MerchantsPage/gam/MegaGamListItem/MegaGamListItem.tsx
- src/components/MerchantsPage/gam/MegaGamListItem/SellerDistributorPair.tsx
Make mega GAM campaigns more mobile-friendly
> Make mega GAM campaigns more mobile-friendly

- src/components/MerchantsPage/gam/CampaignListItem.tsx
- src/components/MerchantsPage/gam/GiftAMealPage.tsx
- src/components/MerchantsPage/gam/MegaGamListItem/MegaGamListItem.tsx
- src/components/MerchantsPage/gam/styles.module.scss
> Modify mega GAM campaign component to allow for inactive styling

- src/components/LightUpChinatown/DonationSection.tsx
- src/components/MerchantsPage/DonationHighlightBox.tsx
- src/components/MerchantsPage/DonationPool.tsx
- src/components/MerchantsPage/gam/CampaignListItem.tsx
- src/components/MerchantsPage/gam/CampaignProgressBar.tsx
- src/components/MerchantsPage/gam/MegaGamListItem/MegaGamListItem.tsx
- src/components/ModalPayment/Modal.tsx
- src/components/ModalPayment/ModalBuyMeal/ModalBuyMealPool.tsx
- src/components/ModalPayment/ModalCardDetails/ModalCardDetails.tsx
- src/components/OwnerPanel/OwnerPanel.tsx
Renamed monetary variable names to include measurement units to avoid confusion between cents and dollars
Some code clean up
> Monetary variable renaming

- src/locales/en/translation.json
Also see [trello card](https://trello.com/c/XXlaDe2f)
> Change luc donationdetail1 text to 14in lantern

- src/components/MerchantsPage/gam/MegaGamListItem/MegaGamListItem.tsx
- src/components/ModalPayment/Modal.tsx
- src/components/ModalPayment/ModalAmount/ModalAmount.tsx
- src/components/ModalPayment/ModalCardDetails/ModalCardDetails.tsx
- src/components/ModalPayment/ModalConfirmation/ModalConfirmation.tsx
- src/components/ModalPayment/ModalMegaGam/ModalMegaGam.tsx
- src/components/ModalPayment/ModalMegaGam/index.ts
- src/components/ModalPayment/ModalMegaGam/styles.module.scss
- src/consts.ts
- src/locales/cn/translation.json
- src/locales/en/translation.json
- src/utilities/hooks/ModalPaymentContext/constants.ts
- src/utilities/hooks/ModalPaymentContext/reducers.ts
- src/utilities/hooks/ModalPaymentContext/types.ts
Resubmitting this PR since my last one was sent 2 weeks ago. More than happy to walk someone through this in detail since it's a pretty big PR.
**Need to do and blockers (back end)**
1. Add the non-profit's fee id to the payment intent (I have a PR for this outstanding)
2. Add campaign id to payment intent (I will have a PRs for this after (1) is approved)
**Need to do but not blockers**
1. Add field for a) whether a campaign will have donation matching to the back end and b) the amount that will be matched(back end)
2. Donation bar amount currently includes the fee amount in addition to the donation (back end)
3. Update Gift-a-Meal payment container (i.e. the place where you enter a meal) now that the payment module is full screen (front end)
**Target not met**
**Target met** …
> Mega gam payment flow

- src/locales/cn/translation.json
- src/locales/en/translation.json
- src/pages/PassportRedemption/Faq.tsx
The only relevant files are faq.tsx and the json files. Redid and localise fetus Alice's SCL food crawl FAQ. Will rebase once Bruce's PR has been merged.
Screenie if "chinese" is chosen (only used sample Chinese for the first two questions)
I think this is an efficient way of handling different things (text formatting, anchor tags) in content
> Localise passport faq 

- src/components/ModalPayment/ModalCardDetails/ModalCardDetails.tsx
Reverting changes because the main SCL donate payment page is breaking due to them
> roll back changes since its breaking donate page

- src/components/MerchantsPage/gam/MegaGamListItem/MegaGamListItem.tsx
Removed blue header and added line breaks in the description
> Mega gam text breaks

- src/components/MerchantsPage/gam/GiftAMealPage.tsx
Added a loading icon to the GAM page while campaigns load
GIF of how the loading screen looks with these changes
https://drive.google.com/file/d/1YluUB7d929B9da3e5EEwvKSF8gQ1Exb9/view?usp=sharing
> Add loading icon gam

- src/components/LightUpChinatown/LightUpChinatownPage.tsx
- src/components/LightUpChinatown/LightUpPartners.tsx
- Removed donate button
- Clean up
> LUC: Remove donate button in banner

- src/components/MerchantsPage/gam/NoCampaignsBox.tsx
- src/components/ModalPayment/ModalAmount/ModalAmount.tsx
- src/consts.ts
- src/locales/cn/translation.json
- src/locales/en/translation.json
Updated copy based on [this trello](https://trello.com/c/kpJzzb9v/810-update-copy-on-gam-general-donation-payment-flow-https-merchantsendchinatownlovecom-gift-a-meal-home-with-the-following-copy-htt).
Cleaned up the code a little and added constants for our sellers Send Chinatown Love and Apex for Youth
Regular donation modal is unchanged
> updated copy of pooled gam

- src/locales/en/translation.json
- src/pages/PassportRedemption/SignIn/uploadScreen.tsx
fixing bugs 
- email screen copy 
- disable upload button after initial click 
- disable submission unless it matches an existing user 
- fix regex for file uploads --> only allows alphanumeric 
- clears inputs in case there are any errors
> fixing upload screen bugs for lny passport

- src/components/LightUpChinatown/LightUpChinatownPage.tsx
- src/components/Navbar/NavBar.tsx
- src/locales/cn/translation.json
- src/locales/en/translation.json
> Remove sticky locals in navbar

- src/components/ModalPayment/ModalAmount/ModalAmount.tsx
- src/locales/cn/translation.json
- src/locales/en/translation.json
This reverts commit c87172152fd4269b4fa4830b8ef84ac1340b8fef, reversing
changes made to 64918a46c8c9e588f424514506aa32b22323077e.
Reverting #471
> Revert accidentally overreaching GAM text swap

- src/components/ModalPayment/ModalCardDetails/SquareCardForm.tsx
- src/utilities/general/StoreImages.tsx
> adding powered by square logo to checkout

- pull_request_template.md
Have a PR template for reference. 
Goal is to provide a framework to help people provide better context.
E.g. I would LOVE links to tickets or other things.
> Added a basic PR template

- src/components/Navbar/NavBar.tsx
- src/locales/cn/translation.json
- src/locales/en/translation.json
> Remove LUC from Dropdown

- src/components/Navbar/NavBar.tsx
> Remove hardcoded mobile dropdown

- src/components/MerchantsPage/MerchantNavBar.tsx
- src/components/MerchantsPage/MerchantsPage.tsx
https://trello.com/c/8cuqL3Ps/702-fix-boc-bocs-location-filtering
fix filtering for bocboc
> #702 fix show queens restaurants under queens

- src/components/App/App.tsx
- src/components/Navbar/NavBar.tsx
- src/locales/cn/translation.json
- src/locales/en/translation.json
```
const dropdownOptions = [
{ url: '/merchants', translation: 'donate', external: false },
{ url: '/gift-a-meal-home', translation: 'gift-a-meal', external: false },
{
url: 'https://www.sendchinatownlove.com/cookbook',
translation: 'cookbook',
external: true,
},
];
```
> adding /cookbook link to main WAYS TO DONATE dropdown

- .github/workflows/deploy.yaml
> adding a manual deploy option

- src/components/MerchantsPage/styles.module.scss
- src/index.scss
Update styling bc it wasn't centered, now it is
> update total merchant styling

- src/components/MerchantsPage/MerchantNavBar.tsx
> fix grid display for filter

- src/components/ModalPayment/ModalCardDetails/ModalCardDetails.tsx
- src/locales/cn/translation.json
- src/locales/en/translation.json
- src/utilities/testing/render.tsx
Reverts sendchinatownlove/sendchinatownlove.github.io#509
> Revert "addressing confirm button not re-enabling on card details edit"

- src/components/Navbar/NavBar.tsx
> adding APAHM-GAM NAV

- src/components/Navbar/NavBar.tsx
- src/components/Navbar/styles.module.scss
Reverts sendchinatownlove/sendchinatownlove.github.io#523
> Revert "fix: navbar open menu no longer broken for some iPhone users"

- src/components/Navbar/NavBar.tsx
> updating zine text

- src/components/Navbar/NavBar.tsx
> update missing reference

- src/components/Navbar/NavBar.tsx
Reverts sendchinatownlove/sendchinatownlove.github.io#540
> Revert "update missing reference"

- src/components/Navbar/NavBar.tsx
Reverts sendchinatownlove/sendchinatownlove.github.io#541
> Revert "Revert "update missing reference""

- src/components/Navbar/NavBar.tsx
> fix text case sensitivity

- src/components/Navbar/NavBar.tsx
zine is done removing reference
> remove zine reference

- .github/dependabot.yml
We're way out of date still on so many things, but this will at least keep us somewhat apace
> Adding dependabot auto-bumps

- src/components/Navbar/NavBar.tsx
> fixed header wonky

- src/App/App.tsx
> make nav default to /
